Move VMA to dissect.archive
fox-it/dissect.hypervisor pull request #46
Opened 2024-11-06 13:43 UTC by Schamper

2024-11-06 14:42 UTC, twiggler approved these changes

2024-11-06 14:47 UTC, twiggler requested changes
Shouldn't `project.scripts` of `pyproject.toml` be adjusted?

2024-11-06 15:46 UTC, Schamper commented
Good point, fixed

2024-11-07 08:49 UTC, twiggler approved these changes

2024-11-07 13:08 UTC, merged